# Dedicated @LFW

[package]
authors = ["Daniel Chaiken <dhchaiken@gmail.com>"]
edition = "2018"
name = "homonym_impl"
version = "0.1.0"

[dependencies]
clap = "2.33.3"
logos = "0.11.4"
regex = "1.4.2"
